USE ROLE ACCOUNTADMIN;

-- creation of warehouse
CREATE WAREHOUSE IT_SUPPORT_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE IT_SUPPORT_WH;

-- database creation
CREATE DATABASE IT_SUPPORT_DB;
USE DATABASE IT_SUPPORT_DB;

-- creating schemas
CREATE SCHEMA RAW;
CREATE SCHEMA PROCESSING;
CREATE SCHEMA ANALYTICS;

-- creating roles 
CREATE ROLE PROJECT_ADMIN;
CREATE ROLE DATA_ENGINEER;

-- warehouse access
GRANT USAGE ON WAREHOUSE IT_SUPPORT_WH TO ROLE PROJECT_ADMIN;
GRANT USAGE ON WAREHOUSE IT_SUPPORT_WH TO ROLE DATA_ENGINEER;

-- DATABASE access 
GRANT USAGE ON DATABASE IT_SUPPORT_DB TO ROLE PROJECT_ADMIN;
GRANT USAGE ON DATABASE IT_SUPPORT_DB TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IT_SUPPORT_DB TO ROLE PROJECT_ADMIN;

GRANT USAGE ON SCHEMA IT_SUPPORT_DB.RAW TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA IT_SUPPORT_DB.RAW TO ROLE DATA_ENGINEER;

GRANT USAGE ON SCHEMA IT_SUPPORT_DB.PROCESSING TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA IT_SUPPORT_DB.PROCESSING TO ROLE DATA_ENGINEER;

GRANT USAGE ON SCHEMA IT_SUPPORT_DB.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA IT_SUPPORT_DB.ANALYTICS TO ROLE DATA_ENGINEER;

GRANT SELECT ON ALL TABLES IN SCHEMA IT_SUPPORT_DB.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA IT_SUPPORT_DB.PROCESSING TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA IT_SUPPORT_DB.ANALYTICS TO ROLE DATA_ENGINEER;


GRANT SELECT ON FUTURE TABLES IN SCHEMA IT_SUPPORT_DB.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA IT_SUPPORT_DB.PROCESSING TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA IT_SUPPORT_DB.ANALYTICS TO ROLE DATA_ENGINEER;

CREATE USER admin_akhil
PASSWORD='Akhil123'
DEFAULT_ROLE=PROJECT_ADMIN
DEFAULT_WAREHOUSE=IT_SUPPORT_WH;

CREATE USER engineer_abhishek
PASSWORD='Abhi123'
DEFAULT_ROLE=DATA_ENGINEER
DEFAULT_WAREHOUSE=IT_SUPPORT_WH;

GRANT ROLE PROJECT_ADMIN TO USER admin_akhil;
GRANT ROLE DATA_ENGINEER TO USER engineer_abhishek;